language: node_js
node_js:
  - "10.15"

services:
  - docker

before_install:
  - docker pull ibmcom/couchdb3:latest
  - docker pull rubinlab/mariadb:latest

install:
  - docker run -p 5984:5984 -d ibmcom/couchdb3 -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin
  - docker run -p 3306:3306 -d rubinlab/mariadb -e MYSQL_DATABASE=epaddb -e MYSQL_USER=pacs -e MYSQL_PASSWORD=pacs -e MYSQL_ROOT_PASSWORD=mymariasecret

before_script:
  - npm ci
  - curl -X PUT localhost:5984/chronicle